sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: gZATmtNs66zlInfrqnYc4j4wMtikxEAs1SuUu6Dj4pINnVVgOAxGmDoQTUHyJR8X5cfLXmyPbV579rMKOqkZSsUAGHXgGugfe/fWiNO+MkSfnvYNZ+GssOC7QCC3oKE8gonGgF6MTyL1/95g0Lq0qcVnXbi37wQQE45EM6o/gDkHvTgexWNBnUpVp7aiaTt8i/TVHov6gTaNMIcb7GqfSE2sG2JhWVRIv98UrFzqQOU6BTt2ZoEo2S0dfHyQiYiRw8YugaYhNANhO6sA4o2SZJndHRIzZ51ivJBa6+q++ZfYHkCSkSoBbNzfKeTC8lRYMtkC9YyRth9TvqcxcXty0cg2plJJqi2x+EwhUFQHromGakXd0cl9Yv4P2TDo+Mmta7H3KC+slroWtAPbXIw5haLvRXOxXdt3OZJwp9CDEi9NppvRiiB1Z48/a1/7gPkLCTWl0ZRSktNrjBt9/EITNHb1R0YPkXJqHIu7J9gYW/ljXE19rFH43mZ6XM+inkwo5TjARRjS2wln8xqackWWsiy+fgw4iIfrQ8Bm+DHskcgCLM+jbcH05QokCQrM5YBic/gekvRgvTLE0BmVS2jnK6x3nM8ZrGyQdFJZkJ5Y1tgbi4SqcFToztqr3I8JwRnSyWfTmLhxvhDcgRZqcih0d3VRKM8H1xNqI5aI9cQ1mAE=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Valley-of-the-Moon_1449
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy